name: Ukesoppgave
description: Mal for en ukesoppgave
title: "Tittel (WW/26)"
labels: ["ukesoppgave"]
projects: ["NKK-IT-Utvikling/42"]
body:
    - type: markdown
      attributes:
      value: |
          **Beskrivelse**
          Kort beskrivelse og screenshots
